VEHICLE_CLASSES = [2, 3, 5, 7]  # car, motorcycle, bus, truck

CONF_THRESHOLD = 0.30

TRACK_MAX_DISTANCE = 60
TRACK_MAX_LOST = 12

SLOW_SPEED_THRESHOLD = 3.0

MIN_VEHICLES_FOR_CONGESTION = 8
MIN_SLOW_VEHICLES_FOR_CONGESTION = 5

ACCIDENT_SLOW_COUNT_THRESHOLD = 8
ACCIDENT_LOW_MOTION_THRESHOLD = 2.0

DISPLAY_WIDTH = 1100

# ROI ratios
ROI_TOP_RATIO = 0.35
ROI_BOTTOM_RATIO = 0.95
ROI_LEFT_RATIO = 0.02
ROI_RIGHT_RATIO = 0.98